[mcp_servers.humwork]
command = "npx"
args = [
  "-y",
  "mcp-remote@latest",
  "https://api.humwork.ai/api/v1",
  "--header",
  "X-API-Key:${HUMWORK_API_KEY}"
]

[mcp_servers.humwork.env]
HUMWORK_API_KEY = "YOUR_API_KEY"
